/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.AtributosTarjeta;
import models.FuncionesCarrito;
import models.Productos;
import models.Tickets;
import views.Menu;

/**
 *
 * @author khalid
 */
public class PasarelaPago extends javax.swing.JDialog {


    private Menu padre;
    private static List<Productos> carrito = new ArrayList<>();
    private static List<AtributosTarjeta> listaDeTarjetas = new ArrayList<>();
    private FuncionesCarrito funcionesCarrito; // Instancia de FuncionesCarrito
     
    public PasarelaPago(Menu ventana, boolean modal) {
        super(ventana, modal);
        padre = ventana;
        initComponents();
        this.setTitle("Pasarela de pago");
        listaDeTarjetas.add(new AtributosTarjeta(1234, LocalDate.of(2025, 12, 1), 123, 100, "Juan Perez"));
        listaDeTarjetas.add(new AtributosTarjeta(5432, LocalDate.of(2025, 10, 4), 456, 500, "Maria Rodriguez"));
        listaDeTarjetas.add(new AtributosTarjeta(1122, LocalDate.of(2025, 8, 23), 789, 200, "Pedro Gomez"));
        listaDeTarjetas.add(new AtributosTarjeta(3322, LocalDate.of(2025, 5, 22), 234, 1500, "Ana Martinez"));
        listaDeTarjetas.add(new AtributosTarjeta(1422, LocalDate.of(2025, 3, 21), 567, 3000, "Carlos Herrera"));
        
        // Inicializar instancia de FuncionesCarrito
        funcionesCarrito = new FuncionesCarrito(padre.getCarrito());
    }
    
    

   

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComprobarBtn = new javax.swing.JButton();
        NumTarjLb = new javax.swing.JLabel();
        FechaVnLb = new javax.swing.JLabel();
        CvvLb = new javax.swing.JLabel();
        NumTarjTxt = new javax.swing.JTextField();
        mesTxt = new javax.swing.JTextField();
        CvvTxt = new javax.swing.JTextField();
        AñoTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SalirBtn = new javax.swing.JButton();
        VolverAtBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ComprobarBtn.setText("Comprar");
        ComprobarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprobarBtnActionPerformed(evt);
            }
        });

        NumTarjLb.setText("Numero Tarjeta");

        FechaVnLb.setText("Introduce la fecha de vencimiento:");

        CvvLb.setText("Cvv");

        jLabel1.setText("Mes");

        jLabel2.setText("Año");

        jLabel3.setText("Introduce tus datos bancarios:");

        SalirBtn.setText("Salir");
        SalirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBtnActionPerformed(evt);
            }
        });

        VolverAtBtn.setText("Volver atrás");
        VolverAtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverAtBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(NumTarjLb, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addComponent(NumTarjTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(CvvLb, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(CvvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(FechaVnLb))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(mesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComprobarBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AñoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))))
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(VolverAtBtn)
                .addGap(47, 47, 47)
                .addComponent(SalirBtn)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumTarjLb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumTarjTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(FechaVnLb, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AñoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CvvLb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CvvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComprobarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalirBtn)
                    .addComponent(VolverAtBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComprobarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprobarBtnActionPerformed
        // TODO add your handling code here:
        
        
         // Obtener los valores introducidos por el usuario
    String numTarjetaStr = NumTarjTxt.getText().trim();
    String mesStr = mesTxt.getText().trim();
    String anoStr = AñoTxt.getText().trim();
    String cvvStr = CvvTxt.getText().trim();

    // Verificar si algún campo está vacío
    if (numTarjetaStr.isEmpty() || mesStr.isEmpty() || anoStr.isEmpty() || cvvStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Convertir los valores de mes y año a enteros
    int mes;
    int ano;
    try {
        mes = Integer.parseInt(mesStr);
        ano = Integer.parseInt(anoStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El mes y el año deben ser números enteros.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Verificar si la fecha de caducidad es válida
    if (mes < 1 || mes > 12 || ano < LocalDate.now().getYear() || (ano == LocalDate.now().getYear() && mes < LocalDate.now().getMonthValue())) {
        JOptionPane.showMessageDialog(this, "La fecha de caducidad no es válida.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Verificar si la longitud del número de tarjeta es válida
    if (numTarjetaStr.length() != 4) {
        JOptionPane.showMessageDialog(this, "El número de tarjeta debe tener 4 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Verificar si el CVV es válido
    if (cvvStr.length() != 3) {
        JOptionPane.showMessageDialog(this, "El CVV debe tener 3 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Verificar si la tarjeta existe en la lista de tarjetas y coincide con los datos introducidos
    boolean tarjetaEncontrada = false;
    for (AtributosTarjeta tarjeta : listaDeTarjetas) {
        if (tarjeta.getNumeroTarjeta() == Integer.parseInt(numTarjetaStr) &&
            tarjeta.getFechaVencimiento().getMonthValue() == mes &&
            tarjeta.getFechaVencimiento().getYear() == ano &&
            tarjeta.getCvv() == Integer.parseInt(cvvStr)) {
            tarjetaEncontrada = true;
            break;
        }
    }

    // Si la tarjeta no se encontró, mostrar un mensaje de error
    if (!tarjetaEncontrada) {
        JOptionPane.showMessageDialog(this, "La tarjeta no existe o los datos no coinciden.", "Error", JOptionPane.ERROR_MESSAGE);
        
    }else{
        try {
                    // Llamar al método comprar de FuncionesCarrito
                    funcionesCarrito.comprar();
                    JOptionPane.showMessageDialog(this, "Compra realizada con éxito. Ticket: ");
                    return;
                } catch (Exception ex) {
                    Logger.getLogger(PasarelaPago.class.getName()).log(Level.SEVERE, null, ex);
                }
    } 


    }//GEN-LAST:event_ComprobarBtnActionPerformed

    private void SalirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirBtnActionPerformed

    private void VolverAtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverAtBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_VolverAtBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PasarelaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PasarelaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PasarelaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PasarelaPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                PasarelaPago dialog = new PasarelaPago(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AñoTxt;
    private javax.swing.JButton ComprobarBtn;
    private javax.swing.JLabel CvvLb;
    private javax.swing.JTextField CvvTxt;
    private javax.swing.JLabel FechaVnLb;
    private javax.swing.JLabel NumTarjLb;
    private javax.swing.JTextField NumTarjTxt;
    private javax.swing.JButton SalirBtn;
    private javax.swing.JButton VolverAtBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField mesTxt;
    // End of variables declaration//GEN-END:variables
}
